// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_angular.Models;

namespace api_angular.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20201018223137_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("api_angular.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Titre = "aspernatur"
                        },
                        new
                        {
                            Id = 2,
                            Titre = "amet"
                        },
                        new
                        {
                            Id = 3,
                            Titre = "sed"
                        },
                        new
                        {
                            Id = 4,
                            Titre = "ipsa"
                        },
                        new
                        {
                            Id = 5,
                            Titre = "ad"
                        },
                        new
                        {
                            Id = 6,
                            Titre = "porro"
                        },
                        new
                        {
                            Id = 7,
                            Titre = "porro"
                        },
                        new
                        {
                            Id = 8,
                            Titre = "rem"
                        },
                        new
                        {
                            Id = 9,
                            Titre = "aut"
                        },
                        new
                        {
                            Id = 10,
                            Titre = "temporibus"
                        });
                });

            modelBuilder.Entity("api_angular.Models.Projet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Git")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Technologie")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2020, 10, 19, 7, 38, 44, 620, DateTimeKind.Local).AddTicks(1992),
                            Description = "Adipisci et cumque assumenda ut et recusandae.",
                            ImageUrl = "https://picsum.photos/640/480/?image=496",
                            Nom = "voluptas"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2020, 10, 19, 14, 42, 44, 537, DateTimeKind.Local).AddTicks(8042),
                            Description = "Occaecati vero placeat voluptas.",
                            ImageUrl = "https://picsum.photos/640/480/?image=5",
                            Nom = "esse"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2020, 10, 19, 19, 40, 40, 933, DateTimeKind.Local).AddTicks(1758),
                            Description = "Qui non est qui blanditiis animi enim unde corrupti praesentium.",
                            ImageUrl = "https://picsum.photos/640/480/?image=1084",
                            Nom = "ea"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2020, 10, 19, 16, 5, 4, 310, DateTimeKind.Local).AddTicks(2079),
                            Description = "Velit nostrum consequuntur cupiditate quibusdam enim.",
                            ImageUrl = "https://picsum.photos/640/480/?image=708",
                            Nom = "quas"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2020, 10, 19, 14, 15, 57, 638, DateTimeKind.Local).AddTicks(5816),
                            Description = "Soluta quae mollitia sit non officiis dicta totam.",
                            ImageUrl = "https://picsum.photos/640/480/?image=895",
                            Nom = "et"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2020, 10, 19, 5, 37, 59, 694, DateTimeKind.Local).AddTicks(2877),
                            Description = "Nihil molestiae dolore dolorem a.",
                            ImageUrl = "https://picsum.photos/640/480/?image=481",
                            Nom = "consequatur"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2020, 10, 19, 4, 32, 42, 989, DateTimeKind.Local).AddTicks(9692),
                            Description = "Esse rerum sit distinctio blanditiis porro odit.",
                            ImageUrl = "https://picsum.photos/640/480/?image=97",
                            Nom = "aut"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2020, 10, 19, 8, 27, 57, 986, DateTimeKind.Local).AddTicks(8526),
                            Description = "Nemo illo quae velit alias consequuntur voluptatem laborum.",
                            ImageUrl = "https://picsum.photos/640/480/?image=404",
                            Nom = "ad"
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2020, 10, 19, 4, 32, 56, 445, DateTimeKind.Local).AddTicks(757),
                            Description = "Magni eveniet accusamus sed minima et enim iusto.",
                            ImageUrl = "https://picsum.photos/640/480/?image=27",
                            Nom = "eum"
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2020, 10, 19, 23, 1, 23, 220, DateTimeKind.Local).AddTicks(3652),
                            Description = "Voluptate culpa cupiditate architecto nesciunt.",
                            ImageUrl = "https://picsum.photos/640/480/?image=279",
                            Nom = "aut"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
