// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_angular.Models;

namespace api_angular.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("api_angular.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Titre = "perspiciatis"
                        },
                        new
                        {
                            Id = 2,
                            Titre = "ipsam"
                        },
                        new
                        {
                            Id = 3,
                            Titre = "quis"
                        },
                        new
                        {
                            Id = 4,
                            Titre = "ut"
                        },
                        new
                        {
                            Id = 5,
                            Titre = "sint"
                        },
                        new
                        {
                            Id = 6,
                            Titre = "rerum"
                        },
                        new
                        {
                            Id = 7,
                            Titre = "qui"
                        },
                        new
                        {
                            Id = 8,
                            Titre = "porro"
                        },
                        new
                        {
                            Id = 9,
                            Titre = "laborum"
                        },
                        new
                        {
                            Id = 10,
                            Titre = "rerum"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
